name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          release-type: "maven"
  build:
    if: ${{ env.ACT || steps.release.outputs.release_created }}
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set version
        id: version
        run: echo "version=$(cat version)" >> $GITHUB_OUTPUT
      - name: Set up JDK 18 (Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/player
          mv player/target/teamgruen-player.jar artifacts/player/
          mv sdk/target/sdk-*.jar artifacts/
          mv player/assets/* artifacts/player/
          zip -r -j artifacts/teamgruen-player.zip artifacts/player
          rm -rf artifacts/*/
      - name: Upload artifact
        if: ( !env.ACT )
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: artifacts/*
  upload-release-artifacts:
    if: ${{ steps.release.outputs.release_created }}
    needs: build
    name: Upload Release Artifacts
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: archives
          path: artifacts
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} artifacts/*
  deploy:
    if: ${{ steps.release.outputs.release_created }}
    needs: build
    name: Deploy
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: archives
          path: artifacts
          file: teamgruen-player.zip
      - name: Upload client
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://sc-upload.justix.dev/api/v1/upload/v${{ needs.build.outputs.version }}?fileName=teamgruen-player.zip'
          method: 'POST'
          timeout: 5000
          customHeaders: |
            {
              "Content-Type": "application/octet-stream",
              "X-API-Key": "${{ secrets.UPLOAD_API_KEY }}"
            }
          file: artifacts/teamgruen-player.zip