name: Release version
on:
  workflow_dispatch:
  push:
    paths:
      - .github/.version
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read .version file
        id: version
        run: echo "::set-output name=version::$(cat .github/.version)"

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts/
          mv */target/*.jar artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: artifacts/*.jar
  create-release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: jars
          pattern: 'artifacts/*.jar'

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ needs.build.outputs.version }}
          release_name: Release ${{ needs.build.outputs.version }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
          files: artifacts/*.jar